#
# Copyright 2020, 2021 Hewlett Packard Enterprise Development LP
#
apiVersion: v2
name: cray-postgres-operator
version: 0.11.2
appVersion: "852f292" # the postgres-operator repo sha
home: "cloud/cray-charts"
description: Cray-specific parent chart of github.com/zalando/postgres-operator
keywords:
  - postgres-operator
  - postgres-operator-ui
dependencies:
  - name: postgres-operator-ui
    Version: 1.6.0
  - name: postgres-operator
    Version: 1.5.0.1
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-postgres-operator/issues/9
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-postgres-operator/pull/8
  artifacthub.io/images: |
    - name: docker-kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.9
    - name: exporter
      image: artifactory.algol60.net/csm-docker/stable/docker.io/wrouesnel/postgres_exporter:0.8.2
    - name: postgres-operator-ui
      image: artifactory.algol60.net/csm-docker/stable/postgres-operator-ui:1.9.1
    - name: postgres-operator
      image: artifactory.algol60.net/csm-docker/stable/postgres-operator:1.9.1
    - name: spilo-12
      image: artifactory.algol60.net/csm-docker/stable/registry.opensource.zalan.do/acid/spilo-12:1.6-p3
artifacthub.io/license: MIT
