#
# Copyright 2020, 2021 Hewlett Packard Enterprise Development LP
#
apiVersion: v2
version: 0.12.1
name: cray-postgres-operator
description: Cray-specific parent chart of github.com/zalando/postgres-operator
keywords:
  - postgres-operator
  - postgres-operator-ui
home: https://github.com/Cray-HPE/cray-postgres-operator
sources:
  - https://github.com/Cray-HPE/cray-postgres-operator
dependencies:
  - name: postgres-operator-ui
    version: 1.6.0
  - name: postgres-operator
    version: 1.5.0.1
maintainers:
  - name: kimjensen-hpe
appVersion: 1.9.1 # use upstream postgres-operator version
annotations:
  artifacthub.io/images: |
    - name: docker-kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.15
    - name: postgres_exporter
      image: artifactory.algol60.net/csm-docker/stable/docker.io/wrouesnel/postgres_exporter:0.8.2
    - name: postgres-operator-ui
      image: artifactory.algol60.net/csm-docker/stable/postgres-operator-ui:1.9.1
    - name: postgres-operator
      image: artifactory.algol60.net/csm-docker/stable/postgres-operator:1.9.1
    - name: spilo-12
      image: artifactory.algol60.net/csm-docker/stable/registry.opensource.zalan.do/acid/spilo-12:1.6-p3
  artifacthub.io/license: MIT
