#
# MIT License
#
# (C) Copyright 2020, 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Full available options can be seen here: https://github.com/zalando/postgres-operator/blob/c1d108a8321190559e4280b440ffe448339f656f/charts/postgres-operator/values.yaml

kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.24.17

postgres-operator:
  image:
    registry: artifactory.algol60.net
    repository: csm-docker/stable/registry.opensource.zalan.do/acid/postgres-operator
    tag: v1.10.1
    pullPolicy: "IfNotPresent"

  podAnnotations:
    sidecar.istio.io/inject: "true"

  podLabels: {}

  # general configuration parameters
  configGeneral:
    docker_image: artifactory.algol60.net/csm-docker/stable/ghcr.io/zalando/spilo-15-test2:3.0-p1
    resync_period: 5m
    enable_pgversion_env_var: false  # needed for rollback to succeed

  # Deploy "postgres_exporter" as sidecar container to "postgres"
    sidecars:
      - name: "exporter"
        image: "artifactory.algol60.net/csm-docker/stable/docker.io/wrouesnel/postgres_exporter:0.8.2"
        ports:
          - name: http
            containerPort: 9187
            protocol: TCP
        resources:
          limits:
          cpu: 500m
          memory: 256M
          requests:
            cpu: 100m
            memory: 200M
        env:
          - name: "DATA_SOURCE_URI"
            value: "localhost:5432/postgres?sslmode=require"
          - name: "DATA_SOURCE_USER"
            value: $(POSTGRES_USER)
          - name: "DATA_SOURCE_PASS"
            value: $(POSTGRES_PASSWORD)
          - name: "PG_EXPORTER_AUTO_DISCOVER_DATABASES"
            value: "true"

  configMajorVersionUpgrade:
    major_version_upgrade_mode: "on"

  # parameters describing Postgres users
  configUsers:
    super_username: postgres

  configKubernetes:
    watched_namespace: "*"
    secret_name_template: '{username}.{cluster}.credentials'
    spilo_privileged: false
    pod_management_policy: "ordered_ready"
    enable_pod_antiaffinity: true
    pod_antiaffinity_topology_key: "kubernetes.io/hostname"
    pod_environment_configmap: "postgres-nodes-pod-env"
    spilo_fsgroup: 103
    enable_pod_disruption_budget: false

  # configure behavior of load balancers
  configLoadBalancer:
    enable_master_load_balancer: false
    enable_replica_load_balancer: false

  # automate creation of human users with teams API service
  configTeamsApi:
    enable_teams_api: false

  # Affinity for pod assignment
  # Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  priorityClassName: csm-high-priority-service

  # Tolerations for pod assignment
  # Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # Node labels for pod assignment
  # Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  configLogicalBackup:
    logical_backup_docker_image: "artifactory.algol60.net/csm-docker/stable/registry.opensource.zalan.do/acid/logical-backup:v1.10.1"
    logical_backup_job_prefix: logical-backup-
    logical_backup_provider: s3
    logical_backup_s3_bucket: postgres-backup
    logical_backup_s3_access_key_id: ""
    logical_backup_s3_secret_access_key: ""
    logical_backup_s3_endpoint: "http://rgw-vip.nmn"
    logical_backup_s3_retention_time: "2 days"
    logical_backup_s3_region: ""
    logical_backup_s3_sse: ""
    logical_backup_schedule: "0 12 * * *"  # everyday at noon
  configConnectionPooler:
    connection_pooler_image: "artifactory.algol60.net/csm-docker/stable/registry.opensource.zalan.do/acid/pgbouncer:master-27"
